### Create a new report

POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
	"model": "corolla",
	"year": 1980,
	"mileage": 100000,
	"lng": 10,
	"lat": 54,
	"price": 500000
}

### Approve an existing report 
PATCH http://localhost:3000/reports/4
content-type: application/json

{
	"approved": true
}