### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Get the current signed in user
GET http://localhost:3000/auth/whoami

### Sign out user
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID

GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=abcd@email.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/3

### Update a user with a given id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "changed@email.com"
}