### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "abcd@email.com",
  "password": "mkcvfkv"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/1