### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "mkcvfkv"
}

### Find a particular user with a given ID

GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=abcd@email.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/3

### Update a user with a given id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "changed@email.com"
}